# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# Basic settings
title: Prototyping
email: mattwatier@gmail.com
description: "Welcome to the ultimate HTML playground—a vibrant space where creativity meets functionality in web design. Our site is dedicated to exploring, experimenting, and showcasing innovative HTML patterns and layouts that breathe life into various projects. Whether you're a seasoned developer seeking inspiration or a newcomer eager to learn the ropes, our repository of cutting-edge designs is your go-to resource. Dive into our collection of meticulously crafted templates and dynamic layouts that promise to elevate your web projects from ordinary to extraordinary. Join us on this journey of discovery and innovation, where each HTML pattern opens the door to endless possibilities in the digital realm."
baseurl: "/Prototype" # Ensure this matches your GitHub repo name exactly, and is case-sensitive
url: "https://mattwatier.github.io" # Your site's base URL
# Social media usernames (optional)
twitter_username: mattwatier
github_username: mattwatier
# Build settings
theme: jekyll-theme-primer # Ensure this theme is supported by GitHub Pages; you can change this to any supported theme
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-github-metadata
# GitHub Pages settings
github:
  - metadata
# Collections
collections:
  netflix_prototype:
    output: true
    permalink: /netflix/:path/
  derubis:
    output: true
    permalink: /netflix_v2/:path/
# SASS/SCSS Settings (optional)
sass:
  sass_dir: _sass

# Exclusions (optional)
# Here, we specify files and folders that Jekyll should ignore.
# We've commented out common exclusions; uncomment as necessary.
#exclude:
#  - Gemfile
#  - Gemfile.lock
#  - node_modules
#  - vendor/bundle/
#  - vendor/cache/
#  - vendor/gems/
#  - vendor/ruby/
# Plugins (if needed, add more plugins here, but ensure they are supported by GitHub Pages)
# For a list of supported plugins, check: https://pages.github.com/versions/
